<a href="https://colab.research.google.com/github/I-ULISES-I/Colabfiles/blob/main/Pr%C3%A1ctica_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica #4. Manipulación de Matrices**

In [32]:
#Importación de la librería NumPy
import numpy as np

#Creación de las matrices.
matrizA = np.random.randint(1, 11, (3, 3))
matrizB = np.random.randint(1, 11, (3, 3))

#Impresión de las matrices.
print("Matriz A:")
print(matrizA)
print("Matriz B:")
print(matrizB)

#Cálculo e impresión de los resultados.
#Suma de ambas matrices.
print("La suma de las matrices es:\n", matrizA + matrizB)

#Resta de la matriz B a la matriz A.
print("La resta de la matriz B a la matriz A es:\n", matrizA - matrizB)

#Multiplicación de la matriz A por 2.
print("La multiplicación de la matriz A por 2 es:\n", matrizA * 2)

#Multiplicación matricial entre ambas matrices.
print("La multiplicación matricial de A por B es:\n", np.dot(matrizA, matrizB))

Matriz A:
[[3 7 5]
 [3 1 6]
 [3 4 1]]
Matriz B:
[[10  9  4]
 [ 7  4  8]
 [ 1  9  8]]
La suma de las matrices es:
 [[13 16  9]
 [10  5 14]
 [ 4 13  9]]
La resta de la matriz B a la matriz A es:
 [[-7 -2  1]
 [-4 -3 -2]
 [ 2 -5 -7]]
La multiplicación de la matriz A por 2 es:
 [[ 6 14 10]
 [ 6  2 12]
 [ 6  8  2]]
La multiplicación matricial de A por B es:
 [[ 84 100 108]
 [ 43  85  68]
 [ 59  52  52]]
